In [1]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
    "Accept-Language": "en-IN,en-US;q=0.9,en;q=0.8",
    "Referer": "https://www.flipkart.com/"
}

1. HTTP headers are metadata sent with a web request that describe the client making the request, such as the browser type and language preferences.
2. Including headers (especially the User-Agent) helps the server identify the request as coming from a legitimate browser rather than a bot(bots are rejected) by servers
3. This is important in web scraping because many websites restrict or block requests that do not contain proper headers.

In [2]:
import requests, time, re
# requests: A Python library used to send HTTP requests and fetch web pages or APIs easily.

# time: A built-in Python module used to control execution timing, such as adding delays between requests to avoid overloading servers.

# re: A Python library for working with regular expressions, used to search, extract, and validate text patterns from data.

import pandas as pd
# pandas: A Python data analysis library used to store, clean, manipulate, and export structured data using DataFrames and Series.
from bs4 import BeautifulSoup
# BeautifulSoup (from bs4): A Python library used to parse HTML/XML documents and extract required data from web pages in a structured and readable way.

laptops = pd.DataFrame() # 

for page in range(1, 51): # to request and fetch all pages present
    print(f"Scraping page {page}...")  # just to check that scrapinf is on

    url = f"https://www.flipkart.com/laptops/pr?sid=6bo%2Cb5g&q=laptop&p%5B%5D=facets.price_range.from%3D40000&otracker=categorytree&p%5B%5D=facets.price_range.to%3D75000&p%5B%5D=facets.brand%255B%255D%3DHP&p%5B%5D=facets.brand%255B%255D%3DDELL&p%5B%5D=facets.brand%255B%255D%3DLenovo&p%5B%5D=facets.brand%255B%255D%3DASUS&p%5B%5D=facets.brand%255B%255D%3DAcer&p%5B%5D=facets.brand%255B%255D%3DApple&p%5B%5D=facets.brand%255B%255D%3DSamsung&sort=recency_desc&page={page}"
    # url here is a dynamic string to later make request to server for a particular page
    webpage = requests.get(url, headers=headers).text 
    #  webpage = requests.get(url, headers=headers).text: Sends an HTTP GET request to the given URL with browser-like headers and --
    #stores the returned HTML content of the webpage as text.
    soup = BeautifulSoup(webpage, "lxml")
    #  soup = BeautifulSoup(webpage, "lxml"): Parses the raw HTML content using the fast lxml parser and converts 
    #it into a searchable BeautifulSoup object for easy data extraction
    time.sleep(2) # pause the program for 2 sec to avoid overloading

    dabba = soup.find_all("div", class_="jIjQ8S") #Finds and stores all HTML div elements with class jIjQ8S, which represent individual laptop product cards on the webpage.
                                                    # it stored in form of list
    # 🚨 Stop if page has no products
    if not dabba:
        print(f"No products found on page {page}. Stopping scraping.")
        break
    # created a dictionary value as empty list
    data = {
        "name": [],
        "avg_rating": [],
        "rating_count": [],
        "reviews_count": [],
        "processor": [],
        "ram": [],
        "os": [],
        "storage": [],
        "display": [],
        "others": [],
        "price": [],
        "discount": [],
        "flipkart_assured": [],
        "product_link": []
    }

    for item in dabba:

        # ---------- NAME ----------
        name_tag = item.find("div", class_="RG5Slk") # to Searches within a single product card get HTML element .that element is div element with given class 
        data["name"].append(name_tag.get_text(strip=True) if name_tag else None) # Extracts and stores the product name text if the HTML tag exists; otherwise, it appends None to keep the data aligned and avoid errors.
        # strip true is to remove extra blank spaces
        # ---------------------------------------------------
        
        # ---------- AVG RATING ----------
        rating_tag = item.find("div", class_="MKiFS6")
        data["avg_rating"].append(rating_tag.get_text(strip=True) if rating_tag else None)

        # ---------- RATING & REVIEWS ----------
        span = item.find("span", class_="PvbNMB")
        if span:
            nums = re.findall(r'[\d,]+', span.text)
            # Here’s how r'[\d,]+' works step-by-step, in a simple way:

            # The regex engine scans the text from left to right, one character at a time.

            # When it finds a character that is either a digit (0–9) or a comma, it starts a match.

            # The + tells it to keep consuming characters as long as they are digits or commas.

            # As soon as a character is found that is not a digit or comma (like a space or letter), the match stops.

            # This process repeats until the entire string is scanned.
            # num is a list of 2 elements
            data["rating_count"].append(int(nums[0].replace(',', '')) if len(nums) > 0 else 0) # if 1st element has a comma then remove it --> change its datatype to int. do this only if something(numbers are present there)  otherwise 0.
            data["reviews_count"].append(int(nums[1].replace(',', '')) if len(nums) > 1 else 0) # same as 1st element
        
        else: # to mention thaat there is no rating count and reviews 
            data["rating_count"].append(0)
            data["reviews_count"].append(0)

        # ---------- FEATURES ----------
        features = []
        ul = item.find("ul", class_="HwRTzP")
        if ul: # if ul has some HTML elements
            li_tags = ul.find_all("li", class_="DTBslk") 
            features = [li.text.strip() for li in li_tags] # features has a list of feature in 1 product card

        data["processor"].append(features[0] if len(features) > 0 else None) # 1st element of feature is processor detail which is extracted here and appended to processor column
        data["ram"].append(features[1] if len(features) > 1 else None) # same as processor
        data["os"].append(features[2] if len(features) > 2 else None) # same (2 else none to avoid error)
        data["storage"].append(features[3] if len(features) > 3 else None) # same 
        data["display"].append(features[4] if len(features) > 4 else None) # same
        data["others"].append(features[5:] if len(features) > 5 else []) # store rest features

        # ---------- PRICE ----------
        price_tag = item.find("div", class_="hZ3P6w DeU9vF")
        data["price"].append(price_tag.text.strip() if price_tag else None)

        # ---------- DISCOUNT ----------
        disc_tag = item.find("div", class_="HQe8jr")
        data["discount"].append(disc_tag.find("span").text.strip() if disc_tag and disc_tag.find("span") else None)

        # ---------- FLIPKART ASSURED ----------
        fa_div = item.find("div", class_="qYp2rh")
        data["flipkart_assured"].append(True if fa_div else False) # to mention if the product is flipkart assured or not

        # ---------- PRODUCT LINK ----------
        a_tag = item.find("a", class_="k7wcnx")
        data["product_link"].append(
            "https://www.flipkart.com" + a_tag["href"] if a_tag else None
        )

    page_df = pd.DataFrame(data)
    laptops = pd.concat([laptops, page_df], ignore_index=True)

print("Scraping completed ✅")

Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
No products found on page 42. Stopping scraping.
Scraping completed ✅

In [3]:
len(laptops)

984

In [4]:
laptops

,name,avg_rating,rating_count,reviews_count,processor,ram,os,storage,display,others,price,discount,flipkart_assured,product_link
0,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel Core 3 Processor (14th Gen),8 GB DDR5 RAM,64 bit Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[1 Year Limited Warranty],"₹50,990",27% off,True,https://www.flipkart.com/asus-expertbook-p1-i3...
1,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel Core 3 Processor (14th Gen),8 GB DDR5 RAM,64 bit Windows 11 Home Operating System,512 GB SSD,35.56 cm (14 Inch) Display,[1 Year Limited Warranty],"₹50,990",27% off,True,https://www.flipkart.com/asus-expertbook-p1-i3...
2,DELL Inspiron 15 (Core i3 14th Gen) Intel Core...,4.3,198,17,Intel Core 3 Processor,8 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD,38.1 cm (15 Inch) Display,[1 Year Onsite Warranty],"₹55,790",10% off,True,https://www.flipkart.com/dell-inspiron-15-core...
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,4.3,1345,109,Intel Core i3 Processor (13th Gen),8 GB DDR5 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[Microsoft Office Home 2024 + Microsoft 365 Ba...,"₹49,990",1% off,True,https://www.flipkart.com/asus-vivobook-15-2025...
4,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,4.3,85,9,AMD Ryzen 5 Quad Core Processor,8 GB LPDDR5 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[Microsoft Office Home 2024 (Lifetime Validity...,"₹46,990",4% off,True,https://www.flipkart.com/asus-vivobook-go-15-2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Lenovo IdeaPad 1 AMD Ryzen 3 Dual Core 3250U -...,4.1,1081,88,AMD Ryzen 3 Dual Core Processor,8 GB DDR4 RAM,64 bit Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[2 Yr Warranty],"₹55,000",6% off,False,https://www.flipkart.com/lenovo-ideapad-1-amd-...
980,DELL Inspiron 3511 Intel Core i3 11th Gen - (8...,4.7,6,0,Intel Core i3 Processor (11th Gen),8 GB DDR4 RAM,64 bit Windows 10 Operating System,1 TB HDD|256 GB SSD,39.62 cm (15.6 Inch) Display,"[MS OFFICE LIFE TIME, 1 YEAR MANUFACTURER WARR...","₹49,946",16% off,False,https://www.flipkart.com/dell-inspiron-3511-in...
981,HP Intel Intel Core i5 12th Gen - (8 GB/512 GB...,4.2,279,20,Intel Core i5 Processor (12th Gen),8 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[1 year (1/1/1) limited warranty includes 1 ye...,"₹64,999",None,False,https://www.flipkart.com/hp-intel-core-i5-12th...
982,ASUS Vivobook S14 OLED Intel Core i5 12th Gen ...,4.4,4725,452,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM,64 bit Windows 11 Operating System,512 GB SSD,35.56 cm (14 Inch) Display,[1 Year Onsite Warranty],"₹70,990",28% off,False,https://www.flipkart.com/asus-vivobook-s14-ole...
983,HP Pavilion Intel Core i5 12th Gen 1240P - (8 ...,4.2,810,64,Intel Core i5 Processor (12th Gen),8 GB DDR4 RAM,64 bit Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,"[Microsoft Office Home & Student 2021, 1 Year ...","₹59,755",23% off,False,https://www.flipkart.com/hp-pavilion-intel-cor...

In [5]:
laptops

,name,avg_rating,rating_count,reviews_count,processor,ram,os,storage,display,others,price,discount,flipkart_assured,product_link
0,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel Core 3 Processor (14th Gen),8 GB DDR5 RAM,64 bit Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[1 Year Limited Warranty],"₹50,990",27% off,True,https://www.flipkart.com/asus-expertbook-p1-i3...
1,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel Core 3 Processor (14th Gen),8 GB DDR5 RAM,64 bit Windows 11 Home Operating System,512 GB SSD,35.56 cm (14 Inch) Display,[1 Year Limited Warranty],"₹50,990",27% off,True,https://www.flipkart.com/asus-expertbook-p1-i3...
2,DELL Inspiron 15 (Core i3 14th Gen) Intel Core...,4.3,198,17,Intel Core 3 Processor,8 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD,38.1 cm (15 Inch) Display,[1 Year Onsite Warranty],"₹55,790",10% off,True,https://www.flipkart.com/dell-inspiron-15-core...
3,ASUS Vivobook 15 (2025) with Office 2024 + M36...,4.3,1345,109,Intel Core i3 Processor (13th Gen),8 GB DDR5 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[Microsoft Office Home 2024 + Microsoft 365 Ba...,"₹49,990",1% off,True,https://www.flipkart.com/asus-vivobook-15-2025...
4,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,4.3,85,9,AMD Ryzen 5 Quad Core Processor,8 GB LPDDR5 RAM,Windows 11 Home Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[Microsoft Office Home 2024 (Lifetime Validity...,"₹46,990",4% off,True,https://www.flipkart.com/asus-vivobook-go-15-2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Lenovo IdeaPad 1 AMD Ryzen 3 Dual Core 3250U -...,4.1,1081,88,AMD Ryzen 3 Dual Core Processor,8 GB DDR4 RAM,64 bit Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[2 Yr Warranty],"₹55,000",6% off,False,https://www.flipkart.com/lenovo-ideapad-1-amd-...
980,DELL Inspiron 3511 Intel Core i3 11th Gen - (8...,4.7,6,0,Intel Core i3 Processor (11th Gen),8 GB DDR4 RAM,64 bit Windows 10 Operating System,1 TB HDD|256 GB SSD,39.62 cm (15.6 Inch) Display,"[MS OFFICE LIFE TIME, 1 YEAR MANUFACTURER WARR...","₹49,946",16% off,False,https://www.flipkart.com/dell-inspiron-3511-in...
981,HP Intel Intel Core i5 12th Gen - (8 GB/512 GB...,4.2,279,20,Intel Core i5 Processor (12th Gen),8 GB DDR4 RAM,Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,[1 year (1/1/1) limited warranty includes 1 ye...,"₹64,999",None,False,https://www.flipkart.com/hp-intel-core-i5-12th...
982,ASUS Vivobook S14 OLED Intel Core i5 12th Gen ...,4.4,4725,452,Intel Core i5 Processor (12th Gen),16 GB DDR4 RAM,64 bit Windows 11 Operating System,512 GB SSD,35.56 cm (14 Inch) Display,[1 Year Onsite Warranty],"₹70,990",28% off,False,https://www.flipkart.com/asus-vivobook-s14-ole...
983,HP Pavilion Intel Core i5 12th Gen 1240P - (8 ...,4.2,810,64,Intel Core i5 Processor (12th Gen),8 GB DDR4 RAM,64 bit Windows 11 Operating System,512 GB SSD,39.62 cm (15.6 Inch) Display,"[Microsoft Office Home & Student 2021, 1 Year ...","₹59,755",23% off,False,https://www.flipkart.com/hp-pavilion-intel-cor...

In [27]:
laptops.to_excel("flipkart_laptops.xlsx", index=False)

In [7]:
!pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\sadiq\appdata\roaming\python\python313\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [28]:
from sqlalchemy import create_engine

username = 'root'            
password = 'your_password'   
host = 'localhost'           
database = 'laptop_analysis'



connection_string = f"mysql+pymysql://root:Sadique%409608@localhost:3306/laptop_analysis"


engine = create_engine(connection_string)

print("Successfully connected to the database!")

Successfully connected to the database!

In [29]:
laptops['others'] = laptops['others'].apply(lambda x: ', '.join(x) if isinstance(x, list) else str(x))


laptops['price'] = laptops['price'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
laptops['price'] = pd.to_numeric(laptops['price'], errors='coerce')


laptops['discount'] = laptops['discount'].astype(str).str.replace('% off', '', regex=False)
laptops['discount'] = pd.to_numeric(laptops['discount'], errors='coerce')


table_name = 'flipkart_laptops'
laptops.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print("Data cleaned and successfully saved to MySQL!")

Data cleaned and successfully saved to MySQL!

In [30]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT COLUMN_NAME, DATA_TYPE 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'laptop_analysis' 
        AND TABLE_NAME = 'flipkart_laptops';
    """))
    for row in result:
        print(row)

('name', 'text')
('avg_rating', 'text')
('rating_count', 'bigint')
('reviews_count', 'bigint')
('processor', 'text')
('ram', 'text')
('os', 'text')
('storage', 'text')
('display', 'text')
('others', 'text')
('price', 'bigint')
('discount', 'double')
('flipkart_assured', 'tinyint')
('product_link', 'text')

In [36]:
from sqlalchemy import text
import pandas as pd


alter_query = text("""
ALTER TABLE flipkart_laptops
MODIFY COLUMN avg_rating FLOAT,
ADD COLUMN brand VARCHAR(50) FIRST,
ADD COLUMN processor_brand VARCHAR(50) AFTER reviews_count,
ADD COLUMN ram_capacity VARCHAR(20) AFTER processor,
ADD COLUMN ram_type VARCHAR(20) AFTER ram_capacity,
ADD COLUMN storage_capacity VARCHAR(20) AFTER os,
ADD COLUMN storage_type VARCHAR(20) AFTER storage_capacity;
""")


update_query = text("""
UPDATE flipkart_laptops
SET 
    brand = SUBSTRING_INDEX(name, ' ', 1),
    processor_brand = SUBSTRING_INDEX(processor, ' ', 1), 
    ram_capacity = SUBSTRING_INDEX(ram, ' ', 1), 
    ram_type = SUBSTRING_INDEX(SUBSTRING_INDEX(ram, ' ', 3), ' ', -1),
    storage_capacity = SUBSTRING_INDEX(storage, ' ', 1),
    storage_type = SUBSTRING_INDEX(SUBSTRING_INDEX(storage, ' ', 3), ' ', -1);
""")

with engine.connect() as conn:
    
    conn.execute(alter_query)
    
    conn.execute(update_query)
    
    conn.commit() 
    
    print("✅ SQL Data cleaning and column rearrangement executed successfully!")


with engine.connect() as conn:
    
    verify_query = text("""
        SELECT * 
        FROM flipkart_laptops 
        LIMIT 5;
    """)
    
    
    preview_df = pd.read_sql(verify_query, conn)


preview_df

✅ SQL Data cleaning and column rearrangement executed successfully!

,brand,name,avg_rating,rating_count,reviews_count,processor_brand,processor,ram_capacity,ram_type,ram,os,storage_capacity,storage_type,storage,display,others,price,discount,flipkart_assured,product_link
0,ASUS,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel,Intel Core 3 Processor (14th Gen),8,DDR5,8 GB DDR5 RAM,64 bit Windows 11 Home Operating System,512,SSD,512 GB SSD,39.62 cm (15.6 Inch) Display,1 Year Limited Warranty,50990,27.0,1,https://www.flipkart.com/asus-expertbook-p1-i3...
1,ASUS,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel,Intel Core 3 Processor (14th Gen),8,DDR5,8 GB DDR5 RAM,64 bit Windows 11 Home Operating System,512,SSD,512 GB SSD,35.56 cm (14 Inch) Display,1 Year Limited Warranty,50990,27.0,1,https://www.flipkart.com/asus-expertbook-p1-i3...
2,DELL,DELL Inspiron 15 (Core i3 14th Gen) Intel Core...,4.3,198,17,Intel,Intel Core 3 Processor,8,DDR4,8 GB DDR4 RAM,Windows 11 Operating System,512,SSD,512 GB SSD,38.1 cm (15 Inch) Display,1 Year Onsite Warranty,55790,10.0,1,https://www.flipkart.com/dell-inspiron-15-core...
3,ASUS,ASUS Vivobook 15 (2025) with Office 2024 + M36...,4.3,1345,109,Intel,Intel Core i3 Processor (13th Gen),8,DDR5,8 GB DDR5 RAM,Windows 11 Home Operating System,512,SSD,512 GB SSD,39.62 cm (15.6 Inch) Display,Microsoft Office Home 2024 + Microsoft 365 Bas...,49990,1.0,1,https://www.flipkart.com/asus-vivobook-15-2025...
4,ASUS,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,4.3,85,9,AMD,AMD Ryzen 5 Quad Core Processor,8,LPDDR5,8 GB LPDDR5 RAM,Windows 11 Home Operating System,512,SSD,512 GB SSD,39.62 cm (15.6 Inch) Display,Microsoft Office Home 2024 (Lifetime Validity ...,46990,4.0,1,https://www.flipkart.com/asus-vivobook-go-15-2...

In [37]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT COLUMN_NAME, DATA_TYPE 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'laptop_analysis' 
        AND TABLE_NAME = 'flipkart_laptops';
    """))
    for row in result:
        print(row)

('brand', 'varchar')
('name', 'text')
('avg_rating', 'float')
('rating_count', 'bigint')
('reviews_count', 'bigint')
('processor_brand', 'varchar')
('processor', 'text')
('ram_capacity', 'varchar')
('ram_type', 'varchar')
('ram', 'text')
('os', 'text')
('storage_capacity', 'varchar')
('storage_type', 'varchar')
('storage', 'text')
('display', 'text')
('others', 'text')
('price', 'bigint')
('discount', 'double')
('flipkart_assured', 'tinyint')
('product_link', 'text')

In [41]:
from sqlalchemy import text
import pandas as pd


update_query = text("""
UPDATE flipkart_laptops
SET 
    -- REGEXP_REPLACE removes anything that is NOT a digit (0-9)
    -- NULLIF ensures that if the result is completely empty, it becomes NULL
    storage_capacity = NULLIF(REGEXP_REPLACE(storage_capacity, '[^0-9]', ''), ''),
    
    -- We allow digits and decimals (.) for RAM and Display
    ram_capacity = NULLIF(REGEXP_REPLACE(ram_capacity, '[^0-9.]', ''), ''),
    display_size_in_cm = NULLIF(REGEXP_REPLACE(display_size_in_cm, '[^0-9.]', ''), '');
""")

alter_modify_query = text("""
ALTER TABLE flipkart_laptops
MODIFY COLUMN ram_capacity FLOAT,
MODIFY COLUMN storage_capacity BIGINT;
""")

with engine.connect() as conn:
   
    conn.execute(update_query)
    
    
    conn.execute(alter_modify_query)
    
    
    conn.commit() 
    
    print("✅ Rogue letters scrubbed and schema modified successfully!")


with engine.connect() as conn:
    verify_query = text("""
        SELECT brand, ram_capacity, storage_capacity, display, display_size_in_cm 
        FROM flipkart_laptops 
        LIMIT 5;
    """)
    preview_df = pd.read_sql(verify_query, conn)


preview_df

✅ Rogue letters scrubbed and schema modified successfully!

,brand,ram_capacity,storage_capacity,display,display_size_in_cm
0,ASUS,8.0,512,39.62 cm (15.6 Inch) Display,39.62
1,ASUS,8.0,512,35.56 cm (14 Inch) Display,35.56
2,DELL,8.0,512,38.1 cm (15 Inch) Display,38.10
3,ASUS,8.0,512,39.62 cm (15.6 Inch) Display,39.62
4,ASUS,8.0,512,39.62 cm (15.6 Inch) Display,39.62

In [42]:
with engine.connect() as conn:
    verify_query = text("""
        SELECT *
        FROM flipkart_laptops 
        LIMIT 5;
    """)
    preview_df = pd.read_sql(verify_query, conn)


preview_df

,brand,name,avg_rating,rating_count,reviews_count,processor_brand,processor,ram_capacity,ram_type,ram,...,storage_capacity,storage_type,storage,display,others,price,discount,flipkart_assured,product_link,display_size_in_cm
0,ASUS,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel,Intel Core 3 Processor (14th Gen),8.0,DDR5,8 GB DDR5 RAM,...,512,SSD,512 GB SSD,39.62 cm (15.6 Inch) Display,1 Year Limited Warranty,50990,27.0,1,https://www.flipkart.com/asus-expertbook-p1-i3...,39.62
1,ASUS,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,4.3,6638,636,Intel,Intel Core 3 Processor (14th Gen),8.0,DDR5,8 GB DDR5 RAM,...,512,SSD,512 GB SSD,35.56 cm (14 Inch) Display,1 Year Limited Warranty,50990,27.0,1,https://www.flipkart.com/asus-expertbook-p1-i3...,35.56
2,DELL,DELL Inspiron 15 (Core i3 14th Gen) Intel Core...,4.3,198,17,Intel,Intel Core 3 Processor,8.0,DDR4,8 GB DDR4 RAM,...,512,SSD,512 GB SSD,38.1 cm (15 Inch) Display,1 Year Onsite Warranty,55790,10.0,1,https://www.flipkart.com/dell-inspiron-15-core...,38.10
3,ASUS,ASUS Vivobook 15 (2025) with Office 2024 + M36...,4.3,1345,109,Intel,Intel Core i3 Processor (13th Gen),8.0,DDR5,8 GB DDR5 RAM,...,512,SSD,512 GB SSD,39.62 cm (15.6 Inch) Display,Microsoft Office Home 2024 + Microsoft 365 Bas...,49990,1.0,1,https://www.flipkart.com/asus-vivobook-15-2025...,39.62
4,ASUS,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,4.3,85,9,AMD,AMD Ryzen 5 Quad Core Processor,8.0,LPDDR5,8 GB LPDDR5 RAM,...,512,SSD,512 GB SSD,39.62 cm (15.6 Inch) Display,Microsoft Office Home 2024 (Lifetime Validity ...,46990,4.0,1,https://www.flipkart.com/asus-vivobook-go-15-2...,39.62

In [43]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT COLUMN_NAME, DATA_TYPE 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = 'laptop_analysis' 
        AND TABLE_NAME = 'flipkart_laptops';
    """))
    for row in result:
        print(row)

('brand', 'varchar')
('name', 'text')
('avg_rating', 'float')
('rating_count', 'bigint')
('reviews_count', 'bigint')
('processor_brand', 'varchar')
('processor', 'text')
('ram_capacity', 'float')
('ram_type', 'varchar')
('ram', 'text')
('os', 'text')
('storage_capacity', 'bigint')
('storage_type', 'varchar')
('storage', 'text')
('display', 'text')
('others', 'text')
('price', 'bigint')
('discount', 'double')
('flipkart_assured', 'tinyint')
('product_link', 'text')
('display_size_in_cm', 'float')

In [45]:
from sqlalchemy import text
import pandas as pd


drop_query = text("DROP TABLE IF EXISTS flipkart_laptops_cleaned;")

create_clean_table_query = text("""
CREATE TABLE flipkart_laptops_cleaned AS
SELECT 
    brand,
    name,
    processor_brand,
    avg_rating,
    rating_count,
    reviews_count,
    ram_capacity,
    ram_type,
    storage_capacity,
    storage_type,
    display_size_in_cm,
    price,
    discount,
    flipkart_assured
FROM 
    flipkart_laptops;
""")


with engine.connect() as conn:
    
    conn.execute(drop_query)
    
   
    conn.execute(create_clean_table_query)
    
    
    conn.commit() 
    
    print("✅ Clean table 'flipkart_laptops_cleaned' created successfully!")


with engine.connect() as conn:
    verify_query = text("SELECT * FROM flipkart_laptops_cleaned LIMIT 5;")
    final_df = pd.read_sql(verify_query, conn)


final_df

✅ Clean table 'flipkart_laptops_cleaned' created successfully!

,brand,name,processor_brand,avg_rating,rating_count,reviews_count,ram_capacity,ram_type,storage_capacity,storage_type,display_size_in_cm,price,discount,flipkart_assured
0,ASUS,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,Intel,4.3,6638,636,8.0,DDR5,512,SSD,39.62,50990,27.0,1
1,ASUS,ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP...,Intel,4.3,6638,636,8.0,DDR5,512,SSD,35.56,50990,27.0,1
2,DELL,DELL Inspiron 15 (Core i3 14th Gen) Intel Core...,Intel,4.3,198,17,8.0,DDR4,512,SSD,38.10,55790,10.0,1
3,ASUS,ASUS Vivobook 15 (2025) with Office 2024 + M36...,Intel,4.3,1345,109,8.0,DDR5,512,SSD,39.62,49990,1.0,1
4,ASUS,ASUS Vivobook Go 15 (2025) with Office 2024 + ...,AMD,4.3,85,9,8.0,LPDDR5,512,SSD,39.62,46990,4.0,1

In [46]:
query_1 = text("""
SELECT 
    brand, 
    COUNT(*) as total_models, 
    ROUND(AVG(price), 2) as average_price
FROM flipkart_laptops_cleaned
GROUP BY brand
ORDER BY total_models DESC;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_1, conn)

df_market_share

     brand  total_models  average_price
0       HP           395       59416.18
1     ASUS           193       61271.53
2   Lenovo           153       63355.01
3     Acer           135       57089.87
4     DELL            99       59222.33
5  Samsung             9       64289.00

In [47]:
# Laptop market place is dominated by HP followed by ASUS and LENEVO with all brands having same AVG Price

In [49]:
query_2 = text("""
SELECT 
    ram_capacity, 
    storage_capacity, 
    COUNT(*) as configuration_count
FROM flipkart_laptops_cleaned
GROUP BY ram_capacity, storage_capacity
ORDER BY configuration_count DESC
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_2, conn)

df_market_share

    ram_capacity  storage_capacity  configuration_count
0            8.0             512.0                  525
1           16.0             512.0                  369
2            8.0             256.0                   41
3           16.0               1.0                   19
4            8.0               1.0                   10
5           12.0             512.0                    8
6            4.0            3962.0                    4
7            NaN               NaN                    3
8           12.0             500.0                    1
9            4.0             512.0                    1
10           8.0            3962.0                    1
11           4.0             256.0                    1
12           NaN             156.0                    1

In [50]:
# The most popular configuration is 8 GB RAM and 512 GB storage

In [51]:
query_3 = text("""
SELECT 
    brand, 
    ROUND(AVG(price / ram_capacity), 2) as cost_per_gb_ram
FROM flipkart_laptops_cleaned
WHERE ram_capacity > 0 -- Prevent division by zero
GROUP BY brand
ORDER BY cost_per_gb_ram ASC;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_3, conn)

df_market_share

     brand  cost_per_gb_ram
0  Samsung          5110.36
1     Acer          5304.58
2     ASUS          5602.35
3   Lenovo          6025.94
4     DELL          6114.83
5       HP          6174.64

In [52]:
# Samsung provide best on avg computing power against money

In [56]:
query_4 = text("""
SELECT 
    CASE 
        WHEN price < 40000 THEN 'Budget'
        WHEN price BETWEEN 40000 AND 70000 THEN 'Mid-Range'
        ELSE 'Premium'
    END as price_tier,
    processor_brand,
    COUNT(*) as total_laptops
FROM flipkart_laptops_cleaned
GROUP BY price_tier, processor_brand
ORDER BY price_tier, total_laptops DESC;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_4, conn)

df_market_share

  price_tier processor_brand  total_laptops
0  Mid-Range           Intel            541
1  Mid-Range             AMD            304
2  Mid-Range      Snapdragon              9
3  Mid-Range      Processor:              3
4  Mid-Range        MediaTek              2
5  Mid-Range         Stylish              1
6    Premium           Intel             98
7    Premium             AMD             22
8    Premium      Snapdragon              4

In [57]:
# Mid range and premium laptops both are dominated by Intel

In [58]:
query_5 = text("""
SELECT 
    flipkart_assured, 
    COUNT(*) as total_products,
    ROUND(AVG(avg_rating), 2) as average_rating,
    ROUND(AVG(reviews_count), 0) as avg_reviews_per_product
FROM flipkart_laptops_cleaned
GROUP BY flipkart_assured;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_5, conn)

df_market_share

   flipkart_assured  total_products  average_rating  avg_reviews_per_product
0                 1             256            4.26                    130.0
1                 0             728            4.02                     52.0

In [59]:
# Only 1/4th of the laptops are assured. If review is taken as sales proxy then assured products has 3 times more sales than unassured products.

In [60]:
query_6 = text("""
SELECT 
    brand, 
    ROUND(AVG(discount), 2) as average_discount_percentage,
    MAX(discount) as max_discount_offered
FROM flipkart_laptops_cleaned
WHERE discount IS NOT NULL
GROUP BY brand
ORDER BY average_discount_percentage DESC;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_6, conn)

df_market_share

     brand  average_discount_percentage  max_discount_offered
0  Samsung                        20.67                  39.0
1   Lenovo                        16.42                  47.0
2     ASUS                        16.05                  61.0
3     DELL                        15.59                  47.0
4     Acer                        13.97                  48.0
5       HP                        10.10                  32.0

In [61]:
# HP provides Lowest discounts

In [62]:
query_7 = text("""
WITH BrandAverages AS (
    SELECT 
        brand, 
        name, 
        price,
        AVG(price) OVER(PARTITION BY brand) as brand_avg_price
    FROM flipkart_laptops_cleaned
)
SELECT 
    brand, 
    name, 
    price, 
    ROUND(brand_avg_price, 2) as average_for_brand
FROM BrandAverages
WHERE price > (brand_avg_price * 1.5) -- Laptops costing 50% more than the brand average
ORDER BY brand, price DESC;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_7, conn)

df_market_share

,brand,name,price,average_for_brand
0,Acer,Acer Swift Neo Office 2024 + M365 Basic Intel ...,92500,57089.87

In [63]:
# only Acer Swift Neo Office 2024 has price greater than 1.5 times avg brand price

In [65]:
query_8 = text("""
WITH RankedLaptops AS (
    SELECT 
        brand,
        name,
        avg_rating,
        reviews_count,
        price,
        DENSE_RANK() OVER(PARTITION BY brand ORDER BY avg_rating DESC, reviews_count DESC) as rank_in_brand
    FROM flipkart_laptops_cleaned
    WHERE reviews_count > 50 -- Filter for reliability
)
SELECT Distinct * FROM RankedLaptops WHERE rank_in_brand <= 3;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_8, conn)

df_market_share

,brand,name,avg_rating,reviews_count,price,rank_in_brand
0,Acer,Acer Swift Go 14 Office 2024 + M365 Basic AMD ...,4.4,110,69999,1
1,Acer,Acer Aspire 3 Intel Core i3 13th Gen 1305U - (...,4.3,286,48990,2
2,Acer,Acer Aspire 7 Intel Core i5 13th Gen 13420H - ...,4.3,174,70990,3
3,Acer,Acer Aspire 7 Intel Core i5 13th Gen 13420H - ...,4.3,174,81999,3
4,ASUS,ASUS Vivobook S14 (2025) with Office 2024 + M3...,4.5,137,63000,1
5,ASUS,ASUS Vivobook S16 OLED (2025) with Backlit Key...,4.5,137,69971,1
6,ASUS,ASUS Vivobook Go 15 OLED AMD Ryzen 3 Quad Core...,4.4,495,45990,2
7,ASUS,ASUS Vivobook Go 15 OLED AMD Ryzen 3 Quad Core...,4.4,495,45990,2
8,ASUS,"ASUS Vivobook Go 15 OLED, with Backlit Keyboar...",4.4,495,59500,2
9,ASUS,ASUS Vivobook S14 OLED Intel Core i5 12th Gen ...,4.4,452,70990,3
10,DELL,DELL Inspiron 3520 Intel Core i3 12th Gen 1215...,4.3,349,50100,1
11,DELL,DELL Inspiron 15 Intel Core i3 12th Gen 1215U ...,4.3,349,50783,1
12,DELL,DELL 15 (Previously Inspiron) (2025) Microsoft...,4.3,302,59990,2
13,DELL,DELL 15 (2025) Microsoft Office Home 2024 Inte...,4.3,88,69990,3
14,DELL,DELL Inspiron 15 (2026) Microsoft Office Home ...,4.3,88,64990,3
15,DELL,DELL 15 (Previously Inspiron) Intel Core i5 13...,4.3,88,62990,3
16,DELL,DELL Inspiron 3530 (2026) Intel Core i5 13th G...,4.3,88,64990,3
17,HP,HP 14s Intel Core i3 11th Gen 1115G4 - (8 GB/2...,4.3,465,53563,1
18,HP,HP 15s Intel Core i3 11th Gen 1115G4 - (8 GB/5...,4.3,465,59800,1
19,HP,HP AMD Ryzen 3 Dual Core 3250U - (8 GB/512 GB ...,4.3,401,49000,2
20,HP,HP Laptop Intel Core i3 12th Gen 1215U - (8 GB...,4.3,385,49870,3
21,HP,HP 15s Intel Core i3 12th Gen 1215U - (8 GB/51...,4.3,385,51266,3
22,Lenovo,Lenovo IdeaPad Gaming 3 AMD Ryzen 7 Octa Core ...,4.5,95,63390,1
23,Lenovo,Lenovo IdeaPad Slim 3 Next Gen AI PC WUXGA IPS...,4.4,139,71990,2
24,Lenovo,Lenovo LOQ Intel Core i5 12th Gen 12450HX - (1...,4.3,145,66490,3
25,Samsung,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,4.5,2082,68251,1
26,Samsung,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,4.5,2082,55311,1
27,Samsung,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,4.4,1235,50990,2
28,Samsung,Samsung Galaxy Book4 Metal Intel Core i7 13th ...,4.4,513,73091,3

In [66]:
# "Top 3" list of laptops for every single brand based on user ratings and review counts.

In [69]:
query_9 = text("""
SELECT 
    brand, 
    name, 
    price, 
    avg_rating, 
    reviews_count
FROM flipkart_laptops_cleaned
WHERE price > 50000 
  AND avg_rating < 4.0 
  AND reviews_count > 20
ORDER BY price DESC;
""")

with engine.connect() as conn:
    df_market_share = pd.read_sql(query_9, conn)

df_market_share

,brand,name,price,avg_rating,reviews_count
0,Acer,Acer TravelLite AMD Ryzen 5 7430U - (8 GB/512 ...,55491,3.9,31
1,Acer,Acer TravelLite AMD Ryzen 5 7430U - (8 GB/512 ...,55491,3.9,31
2,HP,HP Intel Celeron Dual Core N4500 - (8 GB/512 G...,53068,3.8,34
3,HP,HP 15 G10 (2025) AMD Ryzen 3 Quad Core 7320U -...,52690,3.9,21

In [ ]:
# Expensive but low rated Laptops